/**
 * Converte schema.json (introspection) em schema.graphql (SDL canônico).
 *
 * SDL é o formato oficial GraphQL — versionado em git, diff funciona
 * linha a linha, ferramentas tipo `graphql-cli` consomem direto.
 *
 * Implementação minimal: cobre Object/Interface/Union/Enum/InputObject/Scalar
 * + descriptions + deprecation. Não cobre directives (raro em prod).
 */

import type {
  GqlField,
  GqlInputField,
  GqlIntrospectionType,
  GqlSchema,
} from "../types.js";

/** Resolve type ref recursivo (NonNull/List wrappers) → string SDL. */
function typeRef(t: GqlIntrospectionType | null | undefined): string {
  if (!t) return "Unknown";
  if (t.kind === "NON_NULL") return `${typeRef(t.ofType)}!`;
  if (t.kind === "LIST") return `[${typeRef(t.ofType)}]`;
  return t.name ?? "Unknown";
}

function description(d?: string | null, indent = ""): string {
  if (!d) return "";
  // Triple-quoted SDL pra suportar multiline + escape de aspas
  const safe = d.replace(/"""/g, '\\"\\"\\"');
  return `${indent}"""${safe}"""\n`;
}

function formatArgs(args: GqlInputField[] | undefined): string {
  if (!args || args.length === 0) return "";
  const parts = args.map((a) => {
    const def = a.defaultValue ? ` = ${a.defaultValue}` : "";
    return `${a.name}: ${typeRef(a.type)}${def}`;
  });
  return `(${parts.join(", ")})`;
}

function formatField(f: GqlField, indent = "  "): string {
  const desc = description(f.description, indent);
  return `${desc}${indent}${f.name}${formatArgs(f.args)}: ${typeRef(f.type)}`;
}

function formatInputField(f: GqlInputField, indent = "  "): string {
  const def = f.defaultValue ? ` = ${f.defaultValue}` : "";
  return `${indent}${f.name}: ${typeRef(f.type)}${def}`;
}

function formatType(t: GqlIntrospectionType): string | null {
  // Filtra introspection types (__Schema, __Type, etc)
  if (t.name?.startsWith("__")) return null;

  const name = t.name ?? "";
  const desc = description(t.description);

  switch (t.kind) {
    case "OBJECT":
      return `${desc}type ${name} {\n${(t.fields ?? [])
        .map((f) => formatField(f))
        .join("\n")}\n}`;
    case "INTERFACE":
      return `${desc}interface ${name} {\n${(t.fields ?? [])
        .map((f) => formatField(f))
        .join("\n")}\n}`;
    case "INPUT_OBJECT":
      return `${desc}input ${name} {\n${(t.inputFields ?? [])
        .map((f) => formatInputField(f))
        .join("\n")}\n}`;
    case "ENUM":
      return `${desc}enum ${name} {\n${(t.enumValues ?? [])
        .map((v) => `  ${v.name}`)
        .join("\n")}\n}`;
    case "UNION":
      // Schema introspection não retorna possibleTypes nesse query
      // (omitido pra reduzir payload). Marcador quando precisar:
      return `${desc}union ${name}`;
    case "SCALAR":
      // Built-ins (String/Int/etc) não emitidos
      const builtins = new Set(["String", "Int", "Float", "Boolean", "ID"]);
      if (builtins.has(name)) return null;
      return `${desc}scalar ${name}`;
    default:
      return null;
  }
}

export function formatSdl(schema: GqlSchema): string {
  const blocks: string[] = [];
  blocks.push(`# Generated by webscap — ${new Date().toISOString()}\n`);

  // Schema definition (root types)
  const rootBlock: string[] = ["schema {"];
  if (schema.queryType) rootBlock.push(`  query: ${schema.queryType.name}`);
  if (schema.mutationType)
    rootBlock.push(`  mutation: ${schema.mutationType.name}`);
  if (schema.subscriptionType)
    rootBlock.push(`  subscription: ${schema.subscriptionType.name}`);
  rootBlock.push("}");
  blocks.push(rootBlock.join("\n"));

  // Ordem determinística pra diff: alfabética por nome
  const sorted = [...schema.types].sort((a, b) =>
    (a.name ?? "").localeCompare(b.name ?? ""),
  );

  for (const t of sorted) {
    const formatted = formatType(t);
    if (formatted) blocks.push(formatted);
  }

  return blocks.join("\n\n") + "\n";
}
